version: '3.8'

networks:
  embedded-network:
    driver: bridge

services:
  mqtt:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    image: eclipse-mosquitto
    container_name: xanims-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - embedded-network

  api:
    container_name: xanims-api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      NODE_ENV: development
    env_file:
      - ./api/.env
    volumes:
      - ./api:/opt/app
      - /opt/app/node_modules
      - /opt/app/node_modules/.strapi
    ports:
      - "1337:1337"
    networks:
      - embedded-network
    depends_on:
      - mqtt

  ui:
    container_name: xanims-ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://xanims-api:1337
    volumes:
      - ./ui:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
      - embedded-network
    depends_on:
      - api

volumes:
  config:
  data:
  log:
